const darkColor = '#6E6E6E';

export const buttonsData = [
    { 
        label: "(", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false, 
    },
    { 
        label: ")", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "mc", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "m+", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "m-", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "mr", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "+/-", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "%", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "AC", 
        onPress: (setMath, resetOperation) => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: true,
        doubleBox: false, 
    },
    { 
        label: "", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: true, 
    },
    { 
        label: "÷", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: true,
        doubleBox: false, 
    },

    /////////////////////////////////////////////////

    { 
        label: "2ⁿᵈ", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false, 
    },
    { 
        label: "x²", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "x³", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "xⁿ", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "eⁿ", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "10ⁿ", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: false,
        doubleBox: false,  
    },
    { 
        label: "7", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: true,
        doubleBox: false,  
    },
    { 
        label: "8", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: true,
        doubleBox: false,  
    },
    { 
        label: "9", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: true,
        doubleBox: false, 
    },
    { 
        label: "x", 
        onPress: () => setMath(resetOperation()), 
        background: darkColor,
        alwaysDisable: true,
        doubleBox: true, 
    },
    
  ];